### ISSUE TITLE
use requirements.txt format for python dependencies 

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#109]

**Comment by wikfeldt** [comment]
along with instructions on copy-pasting to a file requirements.txt and using the appropriate conda or pip commands with `--file`  option

**Comment by rkdarst** [comment]
I remamed the old binder-environment repo to `software` and testing here:
https://github.com/coderefinery/software/tree/rkdarst/update-conda

so far just environment.yml, though.

**Comment by naoe-tatara** [comment]
It seems that requirement.txt was made by @rkdarst in https://github.com/coderefinery/software in the master branch on the same date as the above comment is made. Should this issue be closed?

**Comment by bast** [comment]
Can be closed. There is another issue open to check that they are still up to date.
