### ISSUE TITLE
Instructions on Vagrant possibly unclear

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#11]
At https://www.vagrantup.com/downloads.html there is no Ubuntu package and at https://www.vagrantup.com/docs/installation/ they imply (?) that you should not use `$ sudo apt-get install vagrant`.

**Comment by pkoskinen** [comment]
I will investigate this matter on Ubuntu, so far using apt-get has proven to be prone to errors, at least with kernel 4.4.0-51. If in doubt, it is wise to skip the installation. The excercises can be revisited later, as they are public.

**Comment by bast** [comment]
Closing issue - not relevant for the upcoming workshop.
