### ISSUE TITLE
Singularity container with everything inside 

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#112]
Built by a helper of the mega-workshop:
https://github.com/ftabaro/singularity-coderefinery2020

**Comment by ftabaro** [comment]
Writing a Dockerfile using the Singularity template is trivial. That would address #94 as well.

**Comment by rkdarst** [comment]
There's also the idea of an conda environment.yml file.  We could make
that first, then distribute it to the singularity/docker files, so
that we don't have to repeat these dependencies...

**Comment by emiliaLipponen** [comment]
I will start making the conda environment.yml file. Do all the dependencies need to be included in the file or only those related to Jupyter lesson? Secondly, is the idea to replace the conda install lines in the Singularity file so that the environment.yml will be used to install all needed dependencies?

**Comment by bast** [comment]
Thanks! As far as I understand:
- all dependencies for a regular workshop
- good idea to install from `environment.yml` inside the container. this way we avoid maintaining these in two places

**Comment by rkdarst** [comment]
I see it's not linked from here, but check this out:
https://github.com/coderefinery/software/

It has a start of stuff, but I don't think it has really been tested extensively or used.

**Comment by bast** [comment]
It would be nice to have but for the moment we will try to go with the Conda environment. In future when we start teaching containers, it would be nice to also provide an image along with it.
