### ISSUE TITLE
Vagrant has problems on Ubuntu

### ISSUE THREAD

**Issue by pkoskinen** [coderefinery/installation#12]
Ubuntu 14 and 16 with Vagrant 1.9.1 can not connect with ssh. Most likely a different version of Vagrant would help. Investigate the issue.

**Comment by pkoskinen** [comment]
Adding the following lines to the vagrantfile will show the graphical GUI, which might give more information:

    config.vm.provider "virtualbox" do |v|
      v.gui = true
    end

One possible cause is the "VT-x/AMD-V hardware acceleration is not available on your system" error, which can be overcome by setting it on in BIOS or using a 32-bit image instead.

In my setup this is not enough alone, the interfaces are not simply working, but I have quite an exotic testing environment, so that could cause it.

**Comment by bast** [comment]
Not relevant - closing.
