### ISSUE TITLE
recommend installing git in conda on windows?

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#120]
From hackmd today:
* When I opened Wordcount environment, there is no git installed by default? The archive command requires it and gave error. 'conda install git' fixed it though
    * We've seen this before: the git installs with its own "git bash prompt", and the anaconda prompt has a different prompt.
    * `conda install git` is probably a good idea to do.

I think this might be on Windows, should we recommend `conda install git` in the anaconda environment, even if we don't expect that to be the main way to use it?

**Comment by bast** [comment]
We have now converged to recommending Git Bash and show how to connect it to Conda and I hope participants will read it.
