### ISSUE TITLE
Test Python after installing bash in Windows

### ISSUE THREAD

**Issue by aless80** [coderefinery/installation#138]
A common pitfall for Windows users is that they cannot run Python/conda. In that case, consider to add a test for python (e.g. `python -V`) in the documentation. Either in the end of the [git installation](https://coderefinery.github.io/installation/git/) or 
in the [bash installation](https://coderefinery.github.io/installation/bash/)

**Comment by annefou** [comment]
We explicitely ask Windows users to test python from git bash (done in python installation; see https://coderefinery.github.io/installation/python/).
