### ISSUE TITLE
Remove any `sudo pip` from the instructions

### ISSUE THREAD

**Issue by aless80** [coderefinery/installation#141]
I see in the [installation/python/](https://coderefinery.github.io/installation/python/) this piece of code:

`$ sudo pip install virtualenv`

I understood that `sudo pip` is very bad practice (you can google this and check stackoverflow), as it can break your OS. It actually happened to me. I suggest change all `sudo pip` with `pip .. --user`

**Comment by bast** [comment]
Thanks! Good catch.

**Comment by annefou** [comment]
fixed with last PR on python installation (kept conda only)
