### ISSUE TITLE
detailed compiler/make/cmake instructions from windows user

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#16]
The following text was sent by a student for the stockholm workshop who went through and documented her steps to install compilers, make and cmake on her windows laptop:

Compiler
-------------

Get your compilers from MinGW (here you have a link on your webpage): click "Download Installer" button on the top right, download mingw-get-setup.exe and install.

Open MinGW installer GUI. In Basic Setup, activate check boxes mingw32-base, mingw32-gcc-fortran, and mingw32-gcc-g++. Click on Installation menu, then "Apply changes". This will install the compilers.

Add MinGW to your user path variable:
In control panel, search for "env", click on "Edit environmental variables for your account". In box for user variables, click PATH, click Edit ..., and add <installation-directory>\bin (probably C:\MinGW\bin) at the end of the variables value, separated from the previous entry by a semicolon.

Restart your computer.

Test installations in bash:
gfortran --version
gcc --version
g++ --version

Make
---------

Get make: go to http://gnuwin32.sourceforge.net/install.html and click on "Package List" link in the Installation section. Download and install make. (Here I may add some more details once the website doesn't throw an error any more)

Add make to your user path variable:
In control panel, search for "env", click on "Edit environmental variables for your account". In box for user variables, click PATH, click Edit ..., and add <location-of-make.exe> (probably C:\Program Files (x86)\GnuWin32\bin) at the end of the variables value, separated from the previous entry by a semicolon.

Restart computer.

Test installation in bash:
make --version

Cmake
----------
Install CMake following this page (here you have a link on your webpage). Click on Download on top right. Click on latest stable release. Get 32 or 64 bit version msi file, install.
Add cmake to your user path variable:
n control panel, search for "env", click on "Edit environmental variables for your account". In box for user variables, click PATH, click Edit ..., and add <location-of-make.exe> (probably C:\Program Files\CMake\bin) at the end of the variables value, separated from the previous entry by a semicolon.
Restart computer.

Test installation in bash:
cmake --version

**Comment by bast** [comment]
Very cool! Thanks! I will integrate it tomorrow.
