### ISSUE TITLE
environment.yml could be called coderefinery.yml or some such, to avoid creating a dir to store it

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#163]
- This would save two steps from install instructions
- But perhaps that directory is useful to put all the rest of the workshop stuff in, so this serves a good pedagogical purpose anyway?
- But then the .yml file would be in some undefined place, and we can no longer easily say "Give the path to it on the command line"

So I am thinking now that we should leave it as it is.  But we can see...

**Comment by bast** [comment]
I thought using a standard name would be good to train using standard naming also for own projects.

**Comment by bast** [comment]
Not relevant anymore once #182 is in.

**Comment by bast** [comment]
#182 solved this
