### ISSUE TITLE
conda: MacOS: does it need to activate the environment?

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#164]
- Linux and Windows show activating the environment by sourcing something
- Is this needed for Mac?

**Comment by wikfeldt** [comment]
@rkdarst do you mean whether `source activate coderefinery` or `conda activate coderefinery` is needed after `conda env create -f environment.yml`? That's definitely needed.

Actually, `conda activate` is recommended over `source activate` now (since conda v 4.4) since it works the same across OSs
