### ISSUE TITLE
Github: it recommends 2FA but doesn't discuss implications for https

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#166]
- It is in the next page, but it should clearly be stated here as well.
- Another alternative is personal access tokens, but I guess the strategic  choice is to *not* use that, because it is much less friendly than ssh keys.
- do we know when password+https will be deprecated?

**Comment by bast** [comment]
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
> Beginning August 13, 2021, we will no longer accept account passwords when authenticating Git operations on GitHub.com

**Comment by rkdarst** [comment]
Yes.

Mainly we need some big warning.  I have a feeling that https is used as an emergency backup for many people, when ssh keys are not set up, probably very very often in a course like coderefinery.  We need a giant warning that if you turn this on, the traditional backup doesn't work.  This is the kind of thing that gives me nightmares about losing a huge number of people early on.

In fact, I might even say that we need to completely re-make the installation videos to take this into account.

On the plus side, with git bash it has command line openssh, so instructions are standard.  This is amazing!  But also means you have to use git-bash (though it seems openssh is in conda, but I guess that leads to other complexities)

Other ideas
- move Github account / ssh connection to above the conda/miniconda stuff

**Comment by bast** [comment]
I agree we should redo the videos.
