### ISSUE TITLE
Meld installation instructions

### ISSUE THREAD

**Issue by harivyasi** [coderefinery/installation#187]
Installation instructions for `meld` may be a bit out of date for Windows. They seem to have a installation package (Meld-3.20.3-mingw.msi) which now installs locally for a user (in Appdata). Plus, it's now a compiled file without an '.exe' ending. For me, after installing it today (06.05.2021), the binary was in:
%localappdata%\Programs\Meld\bin\meld

![image](https://user-images.githubusercontent.com/45761248/117290250-79017280-ae65-11eb-8df9-88ecfb82604c.png)

**Comment by harivyasi** [comment]
I later found the ".exe" in `%localappdata%\Programs\Meld\`.

**Comment by bast** [comment]
Thanks! So the outdated part is this one?
```
$ git config --global mergetool.meld.path "C:\Program Files (x86)\Meld\Meld.exe"
```

**Comment by harivyasi** [comment]
Yes, and I am on a pull request for it.

**Comment by harivyasi** [comment]
Done. It took more digging around than I expected. I was trying to figure out the version where the problem crept in. Seems like only 3.20.3 has the issue. (It is, however, the current default installer at the moment.)

**Comment by bast** [comment]
Thanks so much Shashank for the very careful and valuable work!

**Comment by harivyasi** [comment]
Welcome :)
