### ISSUE TITLE
Python version verification

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#194]
It seems this can fail with "SyntaxError: EOL while scanning string literal":
```
python -c 'import sys; assert sys.version_info.major>=3'
```
Solution then seems to be:
```
python -c "import sys; assert sys.version_info.major>=3"
```

**Comment by lucascondeixa** [comment]
There's no difference between problem and solution.

**Comment by bast** [comment]
The quotes (single vs. double). I haven't verified this but this was reported on hackmd at today's workshop.

**Comment by lucascondeixa** [comment]
Yes, it works for windows when I replaced ' (single quotes) by " (double quotes).

**Comment by bast** [comment]
Great, thanks!

**Comment by ingstra** [comment]
I got that error when using single quotes in the anaconda prompt, but not in git bash (windows). I have a feeling single quotes should work in linux as well, but my old computer broke so I can't test that now. So I guess it's something with the anaconda prompt (I installed miniconda, if that matters).

**Comment by bast** [comment]
Ah yes. We are assuming that participants are in Git Bash. But still good to make this more robust.
