### ISSUE TITLE
Full Anaconda is a heavyweight - consider requiring a more lightweight installation

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#21]
we could consider using the conda constructor (https://github.com/conda/constructor) to create installers for windows, mac and linux containing all packages needed for a workshop. This is more lightweight than anaconda, but larger than miniconda since it contains all required packages (but no more). Here's an example: https://github.com/conda/constructor/tree/master/examples/maxiconda.
Particularly for windows this might be valuable since git-bash and nano can be included, see here:
https://github.com/ostueker/SWC-Conda-Installer/releases/tag/v0.0.5

**Comment by bast** [comment]
Yes! Very interesting - did not know about this.

**Comment by bast** [comment]
Alternatives could be pipenv with a Pipfile.

**Comment by bast** [comment]
It seems to me we have good instructions for Miniconda. Alternatives welcome via PRs but I am closing this old issue.
