### ISSUE TITLE
Verification bash script

### ISSUE THREAD

**Issue by frankier** [coderefinery/installation#218]
We had some people come to the workshop without having set up SSH keys. Small problems with the installation can be helped with during the workshop, but the sooner it's caught, the easier it is to schedule time to fix it. What I suggest is that a bash verification script could be included that would run some tests and then print something like:

```
[✓] Git $VERSION installed
[✓] Anaconda $VERSION installed or [-] Anacode $VERSION may be too old
[✓] CodeRefinery Anaconda environment created
[✓] SSH installed
[✓] SSH key generated
[✘] SSH key set up with GitHub (see: https://coderefinery.github.io/xxx)
```

It could even ask for the GitHub username and test the SSH key had been added. At the beginning of the workshop we could ask people to run it so we could identify who has a partial install and help them e.g. in a break.

**Comment by bast** [comment]
Great idea!

**Comment by samumantha** [comment]
Do we have any idea which conda versions are fine and which are too old? Which should be tested here?

**Comment by bast** [comment]
On the page we say: "Relatively new version of Miniconda3 (less than 3 years old)" but I don't think we know more. So we can decide but the page and the verification script should be consistent.

**Comment by samumantha** [comment]
Does this go into the intended direction? 
https://github.com/samumantha/installation/blob/swi_verification_script/content/installation_verification.sh

**Comment by samumantha** [comment]
So it still needs the version check for conda, anything else coming to mind that is currently not checked?

I can still spend some moments on it in evening

**Comment by bast** [comment]
It should also fail nicely if there is no conda at all. See "bash: line 18: conda: command not found"

I just ran this in an env without any conda:
```console
$ curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/samumantha/installation/swi_verification_script/content/installation_verification.sh | bash

git version 2.38.4 found, good to go
conda NOT found, please follow https://coderefinery.github.io/installation/conda/#conda and then try again
bash: line 18: conda: command not found
coderefinery conda environment NOT found, did you maybe give it another name? Please enter your environment name and then press enter:
bash: line 23: conda: command not found
coderefinery conda environment NOT found, please follow https://coderefinery.github.io/installation/conda-environment/#conda-environment and then try again
ssh keys seem to be setup correctly, good to go
```

**Comment by bast** [comment]
Another improvement could be that in the output we say: "week 1: ..." and "week 2: ..." so that if something fails that we only need in week 2 that people don't panic. Also some participants are there only for week 1.

**Comment by samumantha** [comment]
And now I realized that the script exits when something is not found, ie if someone wants to join only week2 and does not have ssh keys set up, then they'll not see week 2 checks.

Should this be a user prompt maybe?
"Which parts of the coderefinery workshop do you plan to attend (1/2/both)" and then show only necessary?

**Comment by samumantha** [comment]
Note on conda text: version 4.8 is approximately 3 years old. I have not tested if this is a real "turning point".

**Comment by bast** [comment]
Thanks a lot! I will test it out. This is great help.

**Comment by bast** [comment]
Reopening. Still needs more testing and needs to be documented.
