### ISSUE TITLE
macOS default shell is apparently zsh since ~2019

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#232]
> https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features

I'm not sure what this means for the instructions, but shell-and-git does say that the macos default shell is bash so other assumptions might be in there.

**Comment by bast** [comment]
"Starting with macOS Catalina, your Mac uses zsh as the default login shell"

https://support.apple.com/en-au/HT208050
