### ISSUE TITLE
Numbered requirements table

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/installation#234]
https://github.com/coderefinery/installation/blob/main/content/index.rst

Could have numbers. They are important in lists in other than nordic countries.

**Comment by bast** [comment]
I find the table hard to visually parse already now. Thinking on how to simplify it.

Do you mean here that the table is used in workshops outside of CodeRefinery or what do you mean by "in lists in other than nordic countries"?

**Comment by bast** [comment]
Closing. But please re-open if still relevant.
