### ISSUE TITLE
Preparation: understand files and directories

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#237]
This isn't installation but some sort of preparation / shell practice.

People should have some understanding of file and directory structure.  mapping terminal to file browser.  Being in or not in a directory.  etc.

I'm not sure if this should go here or somewhere else (like the shell crash course)

**Comment by bast** [comment]
Dropping this issue. We will recommend beginners to not follow in the terminal if they are completely new to the terminal.
