### ISSUE TITLE
"Choosing the SSH executable" is not in Windows git installation steps

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/installation#253]
![IMG_1117](https://github.com/coderefinery/installation/assets/39948154/79f8860e-aa95-4b2f-ab89-98d33fe72077)
![IMG_1117 (1)](https://github.com/coderefinery/installation/assets/39948154/20d16718-0634-4db3-af7c-72474890f31f)

**Comment by rkdarst** [comment]
use bundled openssh worked

**Comment by rkdarst** [comment]
Upcoming PR will suggest bundled ssh option.
