### ISSUE TITLE
"Configuring experimental options" is not in Windows Git installation steps

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/installation#254]
![IMG_1118](https://github.com/coderefinery/installation/assets/39948154/ba5f9bb2-3109-4a60-8baa-231685374cc6)
![IMG_1118 (1)](https://github.com/coderefinery/installation/assets/39948154/bc580c34-4738-4709-83d6-dfb35f41d62d)

**Comment by rkdarst** [comment]
Upcoming PR will suggest to not enable either.
