### ISSUE TITLE
"GitHub account" instructions could be before "Shell and Git"

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/installation#255]
Especially as it states "We assume that you have: • Signed up for a GitHub account"

**Comment by MatiasJJ** [comment]
Also SSH connection to github could be handled before maybe?

**Comment by bast** [comment]
> Especially as it states "We assume that you have: • Signed up for a GitHub account"

Where exactly does it say that? Motivation to start with Git and shell is that on first day we don't need GitHub yet.

**Comment by rkdarst** [comment]
I think this was removed in df91158 (9 september).  Can be closed?
