### ISSUE TITLE
windows: conda from git bash

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#267]
This doesn't work for an Anaconda install (as opposed to miniconda?  As opposed to a fresh Anaconda install?  I don't know what the condition is):
```
echo ". '${PWD}'/conda.sh" >> ~/.bashrc
```

Because the conda.sh has this in it:
```
export CONDA_EXE='/cygdrive/c/Users/USER/Anaconda3/Scripts/conda.exe'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='C:\Users\USER\Anaconda3\python.exe'
```
... and looking at `CONDA_PREFIX`, git-bash doesn't have `/cygdrive/` before the `/c` directories, so `conda --version` or any conda commands.

**Comment by rkdarst** [comment]
Testing from a fresh install on a new laptop (with git-bash installed first), it does work.  I'm not sure what the problem is.

**Comment by bast** [comment]
Closing this issue as we will probably not hit this problem. We will recommend beginners to follow week 2 by watching and asking, instead of in their own terminal.
