### ISSUE TITLE
Idea: make "ask a colleague/helper to go over [checklist] with you" an item

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#271]
As for setup, we could add a strong recommendation to go over the setup with a colleague.  We could even make a separate quick checklist for the colleague/helper to check the setup.

This comes from lessons learned about role of helpers before/after, instead of just during, the workshop.  Could also help with setup and get people talking in advance, which they will hopefully continue to do later.

(this would probably be mentioned in installation, but also mentioned on the main workshop page in a broader context).

**Comment by bast** [comment]
Excellent idea!
