### ISSUE TITLE
Windows: visibility of anaconda installation in the git bash

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#33]
Windows users who install Anaconda need to start the Anaconda shell to see the Python packages. But if they start the Git bash, they don't see these unless they edit the PATH. We need to describe how to do that or make that smoother.

**Comment by rkdarst** [comment]
+1

Also anaconda has git according to the windows package list. No bash, though, so we probably don't want to fully use anaconda for git talks too.

**Comment by bast** [comment]
I think this is now solved in https://coderefinery.github.io/installation/troubleshooting/.
