### ISSUE TITLE
Basics on editors

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/installation#44]
some basics about terminal editors.
Suggestion NANO and VI/VIM. EMACS is too much if you do not know how to use an editor on the terminal. Same time, if you are a EMACS user then you will not need this section.

**Comment by bast** [comment]
Both Emacs and Vim are way too much if people start at the workshop. We should mention a couple of options, motivate why editors are important, and perhaps give a sentence about each of them and let people choose.
