### ISSUE TITLE
Make it easier to see "how to verify the installation"

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#59]

**Comment by wikfeldt** [comment]
solved in a number of commits: 
d3717dbd5802a3db3feecd1af26696d1632cf2c1
1d6e98ac7d31b41b02b417afe6051d558d3831c9
a126b76beb3544f00f85706bcad34f4fa04db683
06e3d299403bad717365ea399f6e7901e6a427c1
5f5d8ccef477564328157120a818923693eb807a
