### ISSUE TITLE
create installers for linux/osx/windows using conda constructor

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#64]
a guide: https://support.anaconda.com/customer/en/portal/articles/2781645-conda-exporting-creating-environments-and-installers

**Comment by annefou** [comment]
Is it to replace 'Installing required packages' section? It is a very good idea. I am happy to work on it.

**Comment by bast** [comment]
IIUC we would not replace everything but offer a compact alternative - in other words I think we should not force participants into conda but those who have it could get a "one line install". Or how do you all see it?

**Comment by wikfeldt** [comment]
this would be more compact than that, people would not need to have conda pre-installed. The installer installs everything under a directory in your home folder, including conda, python, pip, and the packages.

**Comment by wikfeldt** [comment]
i started looking at this this weekend, but have some "Error: File XX found in multiple packages"  errors for this construct.yaml file:
```
name: coderef-installer
version: 0.1
channels:
  - bioconda
  - conda-forge
  - defaults
specs:
  - python 3*
  - numpy
  - matplotlib
  - jupyterlab
  - ipywidgets
  - pandas
  - seaborn
  - sphinx
  - pytest
  - pycodestyle
welcome_image: logo.png     [win] 
```

**Comment by Sabryr** [comment]
I would recommend having conda (or miniconda) installed first.  Then use conda create or conda install. Then you will get instlation and configuration errors for conda first. Once conda is installed, debugging conda package error are easier. For example if a two packages in the conda config requiring different versions of numpy would be a hard issues to debug in a all-in-one solution

**Comment by annefou** [comment]
I don't think it is easy if you have multiple channels. However, I am not sure it is required. I created a conda installer on windows with the following construct.yaml:

name: coderef-installer
version: 0.1
channels:
  - http://repo.anaconda.com/pkgs/main/

specs:
  - python 3*
  - numpy
  - matplotlib
  - jupyterlab
  - ipywidgets
  - seaborn
  - sphinx
  - pytest
  - pycodestyle
welcome_image: cr-logo.png     [win]

Also it looks like we need to run conda construct on each OS to get the corresponding conda installer.

**Comment by annefou** [comment]
I tested the installer on a brand new windows machine and it works perfectly. Do you want to add this windows installer to the setup instruction?

**Comment by wikfeldt** [comment]
great that it works, thanks for testing! But what about snakemake, which is in the bioconda channel?

**Comment by annefou** [comment]
I think we can use a postinstall:

post_install: snakemake.sh            [unix]
post_install: snakemake.bat           [win]

and in snakemake.sh
#!/bin/bash
$PREFIX/bin/conda install -c bioconda snakemake

it works well for linux (snakemake is then available) but I don't know how to write .bat file for windows...

**Comment by naoe-tatara** [comment]
IIUC, this is not presented in the installation guide. Should it be, evt. after testing this still works and fulfills requirements of the CR standard workshops?

**Comment by bast** [comment]
My understanding is that this is now not relevant anymore since we have now https://coderefinery.github.io/installation/conda-environment/?
