### ISSUE TITLE
Should we still keep python 2.7?

### ISSUE THREAD

**Issue by annefou** [coderefinery/installation#66]
*If you have a strong preference for version 2.7 that will mostly work as well, except for the Snakemake package which requires Python3.*

We are teaching best practices so I feel it is odd to keep this statement in 2019.
Considering python 2.7 EOL is approaching, I would suggest we make a strong statement and tell our attendees to move to python 3. 
What do you think?

**Comment by bast** [comment]
I agree. One thing less to test and maintain and for me Python 2 is really history.

**Comment by blankdots** [comment]
Maybe also because python 2.7 ("the" python 2 version) is going to be retired in 2020 https://pythonclock.org/
