### ISSUE TITLE
document a solution for git bash/ anaconda prompt and make it findable

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#70]
By default Git bash cannot see Python and Anaconda prompt cannot see Git.

We have some info on setting paths (https://coderefinery.github.io/installation/troubleshooting/) but:
- this sometimes does not work
- it is almost impossible to find, not linked from any place, try to locate it from the participants' perspective

This is a problem for at least 3 people at each workshop and makes us lose time so we need a bulletproof solution.

My best experience so far is to set it in `.bashrc` in the Git bash prompt.

**Comment by Sabryr** [comment]
I could investigate a solution to have winbash inside a conda environment.  i.e. have python, winbash, git .... etc in one conda env.

**Comment by bast** [comment]
I think the "minimum viable product" is a `.bashrc` solution that is findable. But more elegant solutions are welcome.

**Comment by Sabryr** [comment]
I do not think there is a .bashrc in windows

**Comment by annefou** [comment]
when git bash is installed, we have .bashrc on windows and one can add python to the path.

However, the best/easiest on windows is to tick the box "Add Anaconda to my PATH environment vairable". It looks scary because it says it is not recommended but it works perfectly.

**Comment by bast** [comment]
Yes, in Git bash .bashrc is understood.

**Comment by bast** [comment]
Stealing this from Sabry. We really need a solution for this. I don't want to go to another workshop where we struggle with this.

**Comment by annefou** [comment]
Lately I suggested to install git through anaconda; it works very well.

**Comment by bast** [comment]
I will recommend this route.

**Comment by wikfeldt** [comment]
@annefou is the idea that if someone installs git through conda then git becomes available in anaconda prompt? 
in other words this is not a fix to git-bash problems, but an alternative shell that windows users can use

**Comment by annefou** [comment]
Yes it is then available with conda prompt same as when using snakemake. 

For coderefinery workshops, it should be fine, isn't it? 
________________________________________
