### ISSUE TITLE
Include "exercises" in installation instructions

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#73]
At the bottom of each installation instruction, there should be a "test your installation" which shows what can be done in order to show it works.  A command to run to get started.  The main point isn't only to show it's installed properly, but to have people learn the instructions for using the software: e.g. for git, how to open the Git bash prompt and type a command.

It could also test some relevant background information, though there isn't much to do about it if they don't have it.

We can include note that "if these tests don't work, don't panic... just try to come a bit early and let us know of the problem so we can fix in advance."

**Comment by bast** [comment]
I agree, this would be super.
