### ISSUE TITLE
Link to some shell crash course

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#75]
Include a shell crash course that has at least the commands of: ls, cd, mv, cp, rm, mkdir.  And nano/man.  Preferably a link to some sort of video tutorial.

This may be too involved, but my attempt at a shell tutorial video for these purposes (can be made even shorter, this is for level C scicomp):
https://drive.google.com/file/d/1QlDmCIHggX533cJLiRnEfBbvENWz50v9/view

swcarpentry material could work but I expect it's too long to be useful for a fast crash course.

**Comment by wikfeldt** [comment]
that's a very good idea. we need a ~10 minute screencast or lesson on basic shell, since that's a prerequisite for the workshops
