### ISSUE TITLE
`pip install snakemake` fails on Python 3.7 due to datrie module

### ISSUE THREAD

**Issue by janusvm** [coderefinery/installation#80]
It looks like the PyPI version of `datrie` isn't compatible with Python 3.7;

> `pip3 install datrie` fails with Python 3.7. Install from git is a workaround:
> ```sh
> pip3 install git+https://github.com/pytries/datrie.git
> ```

_Originally posted by @sjackman in https://github.com/pytries/datrie/issues/52#issuecomment-464977050_

While the issue can be fixed by using `conda`, perhaps `pip` instructions should be added for those who don't use a `conda` installation.

**Comment by bast** [comment]
Thanks Janus! I agree that it would be good to also provide a pip route to this.

**Comment by bast** [comment]
I fell into this trap now myself when going through the material (I use venv). I will soon send a patch to the docs.

**Comment by sjackman** [comment]
Please post your experience on https://github.com/pytries/datrie/issues/52. This issue needs a bump.

**Comment by bast** [comment]
Good suggestion and thanks for your workaround there - I will add a comment there.

**Comment by sjackman** [comment]
Thanks!

**Comment by bast** [comment]
We now install only `snakemake-minimal` and test this on Python 3.7 and installation seems to work: https://github.com/coderefinery/software/blob/main/.github/workflows/test-pip.yml
