### ISSUE TITLE
Make sure Windows users can run Git and Python in the same environment

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#83]
This is a problem at every workshop and I would like to not deal with this during the workshop but make it bulletproof before.

**Comment by wikfeldt** [comment]
on the page https://coderefinery.github.io/installation/troubleshooting/ we describe how python can be enabled in git-bash, if it's not already working. Does the suggested solution always work, or are there other possible problems we should document?

**Comment by rkdarst** [comment]
What about the idea of installing git through anaconda - I remember
hearing that before.

**Comment by bast** [comment]
Problem with the troubleshooting page: it is difficult to find or even know that it exists.

Git can indeed be installed through Anaconda and this may be the easiest solution but then we have to be careful with commands like "ls" (which would be "dir" in Anaconda prompt IIRC). We have to be careful with unix commands anyway so perhaps this is not a blocker.

**Comment by bast** [comment]
(I plan to work on this the following week to make this smoother. I will self-assign once I start)
