### ISSUE TITLE
Workshop installation for Windows

### ISSUE THREAD

**Issue by annefou** [coderefinery/installation#90]
I started from scratch and followed the instructions found at https://coderefinery.org/workshops/2019-11-19-stockholm/

Honestly I found it sometimes a bit unclear; difficult to follow (as we always have three cases and windows is always last...) and not always easy to test (commands are usually not named properly (no .exe, etc).

Setup for installation Git-bash has slightly changed (there is now a question about ssh* and the default  is incorrect). It is well explained in the Carpentries setup.

I would recommend:
- Ask our attendees to follow Carpentries workshop setup to install git-bash, Python and R: the main advantage is that is it more likely to be up to date (many more workshops and users following and correcting setup instructions).

https://github.com/carpentries/workshop-template (http://carpentries.github.io/workshop-template/).

Then CodeRefinery specific setup:
- Install additional python packages (https://coderefinery.github.io/installation/python/). I would also add anaconda-navigator (need to show how to add channels) for installing and managing packages (as it is quite nice for managing mulitple conda environment)
- When installing Anaconda with python 3.7, I only had to install:
         * sphinx_rtd_theme
         * snakemake-minimal
         * nbdime
         * jupyterlab-git (I don't think jupyterlab github is necessary anymore)

I think jupyterlab-manager is deprecated is not required; management of extension in jupyterlab is available by default in the latest version of jupyterlab.

All jupyterlab extensions are enabled automatically (and can also be controlled in jupyterlab through the extension manager). When something needs to be build etc., a window pops up and ask you to confirm to build the extension. Then everything works fine.

I recommend to switch from Powershell to Git-bash in JupyterLab. This can be done by updating jupyter configuration (C/Users/annefou/.jupyter/jupyter_notebook_config.py):

c.NotebookApp.terminado_settings = {
    'shell_command': ['C:\\Program Files\\Git\\bin\\bash.exe']
}​

This allows to have a good integration of git/github in Jupyterlab (this may be better than having multiple installation of git via conda).

Finally, I recommend to start jupyterlab from anaconda-navigator. 

- For Visual diff tools, I recommend the usage of p4merge (instead of meld). 

git config --global merge.tool p4merge

git config --global mergetool.p4merge.path "C:/Program Files/Perforce/p4merge.exe"

https://www.perforce.com/downloads/visual-merge-tool​

**Comment by bast** [comment]
Thanks Anne for these observations and recommendations. I have nothing against putting Windows first in the instructions. Now we need to turn these into pull requests.

**Comment by annefou** [comment]
Yes. That's my next task!

**Comment by naoe-tatara** [comment]
@annefou and @bast : if I understand correctly, the suggestion above is not reflected in the current installation guide, but do you (@annefou ) work on this on a branch or your fork? If not, I will try to implement the suggestion above in the revision work for the upcoming workshop (May 2021).

**Comment by bast** [comment]
It is also my understanding that this is not yet reflected in our install guide and this can be an additional route (but then we have 3?).

**Comment by annefou** [comment]
Yes that was my plan... But I haven't started. When do we need to send setup instructions to attendees?

**Comment by naoe-tatara** [comment]
We will send acceptance notification after the soft deadline of 26th April, so it will be the best if the works are done within this week. Myself and Radovan are responsible for this work (I think I have the main responsibility, though) and I try using as much time as possible on this this week. So probably I will be back to you to ask if there are anything unclear. Is this OK for you?

**Comment by bast** [comment]
Is this issue still relevant after the page reorganization?

**Comment by naoe-tatara** [comment]
I believe that it is @annefou that should give a final decision, but in my understanding it is not relevant anymore and this issue can be closed.

**Comment by annefou** [comment]
yes... Thanks for your great job!
