### ISSUE TITLE
need account removal instructions for hackmd.io

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#91]
can't find it on website, but support email is hackmdio@gmail.com

**Comment by bast** [comment]
Wow. A bit surprising that they use a gmail address.

**Comment by naoe-tatara** [comment]
do we need this? (does this mean if you are logged on GitHub, then your user name is automatically shown in HackMD and thus not anonymous??)

**Comment by bast** [comment]
I think the concern here is not primarily whether users are anonymous but they may think that they need to login to be able to edit (especially if we forget to make it world-editable) and then by logging in via GitHub they create an account. So it's more about the account creation, not so much about anonymity.

**Comment by naoe-tatara** [comment]
Then it is rather for us to ensure that the HackMD is editable by anyone, right? In that sense, we can close this issue?

**Comment by bast** [comment]
Yes it can be closed. Perhaps a follow-up before closing could be to:
- document clearly to learners that they don't need to sign-up/log-in to participate
- instructions for hackmd lead should contain a step to enable write permissions before the course

**Comment by naoe-tatara** [comment]
OK, then I would suggest this as an issue in the manual repo.
