### ISSUE TITLE
git can also be installed with conda

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/installation#93]
should we include this as an alternative? might make sense to use conda for as much as possible, for simplicity for participants

**Comment by bast** [comment]
Yes but we already have something: https://coderefinery.github.io/installation/git/#installation-using-conda

**Comment by wikfeldt** [comment]
ah yes, it's there for windows. But i think it's relevant to add the conda option also to the OSX instructions, because installing the latest mavericks installer from a webpage (current OSX recommendation) is not as natural in OSX as "apt-get install" is in linux

**Comment by bast** [comment]
Fully agree, also on Linux and macOS it can be a nice alternative.
