### ISSUE TITLE
Provide Docker image with everything that we will use during workshop

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#94]
So that we eat our medicine and offer a reproducible environment independent of the operating system. This does not have to be the default but it would be great to offer this as option for those who want to try Docker and don't want to pull quite a list of packages into their system environment.

The install instructions could then show how to install Docker (see #92) and how to use our image.

**Comment by wikfeldt** [comment]
totally agree, we should provide a container image. 
But we should perhaps also make it even clearer that installing into system environment isn't necessary if conda environments are used. Actually, we should provide a requirements.txt file as well...

**Comment by bast** [comment]
100% agree. I just re-discovered an issue on this: #87.

**Comment by bast** [comment]
I still think this is a good idea but it hasn't happened and we rather went for Conda. We can always add this in future.
